[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

solc_version = '0.8.26'
evm_version = "cancun"
optimizer_runs = 800
via_ir = false
ffi = true

# RPC URLs
[rpc_endpoints]
base = "https://mainnet.base.org"
base-sepolia = "https://sepolia.base.org"